import { useState } from 'react'
import { Activity, Building2, Check, ChevronRight, CircleDollarSign, Filter, Plus, Search, ShieldCheck, Store, UserPlus, UsersRound } from 'lucide-react'
import { Badge, Button, Field, Metric, Modal, PageHeader, Section, Toast } from '../components/Ui'

type AdminSection = 'global' | 'markets' | 'admins'

const markets = [
  { id: 1, name: 'Mercadinho Coutinho', city: 'Fortaleza, CE', user: 'coutinho', sales: 'R$ 24.680', lastAccess: 'Agora', active: true },
  { id: 2, name: 'Mercantil São Lucas', city: 'Caucaia, CE', user: 'saolucas', sales: 'R$ 18.420', lastAccess: 'Há 12 min', active: true },
  { id: 3, name: 'Mercadinho da Rosa', city: 'Maracanaú, CE', user: 'rosa.mercado', sales: 'R$ 12.905', lastAccess: 'Há 1h', active: true },
  { id: 4, name: 'Box do Zé', city: 'Fortaleza, CE', user: 'boxdoze', sales: 'R$ 0', lastAccess: '02 jul', active: false },
]

export function AdminPage({ section }: { section: AdminSection }) {
  const [modal, setModal] = useState<'market' | 'admin' | 'inactivate' | null>(null)
  const [selectedMarket, setSelectedMarket] = useState<(typeof markets)[number] | null>(null)
  const [toast, setToast] = useState('')

  if (section === 'admins') {
    return <div className="page"><PageHeader eyebrow="Acesso global" title="Administradores" description="Contas autorizadas a gerenciar toda a plataforma." actions={<Button variant="primary" icon={<UserPlus size={18} />} onClick={() => setModal('admin')}>Novo APP_ADMIN</Button>} /><div className="admin-list"><div className="admin-card"><span className="customer-avatar">CO</span><div><strong>Coutinho Oliveira</strong><small>admin@mybox.com · admin.mybox</small></div><Badge tone="success">Ativo</Badge><span><small>Último acesso</small><b>Agora</b></span><ChevronRight size={17} /></div><div className="admin-card"><span className="customer-avatar">MS</span><div><strong>Marina Silva</strong><small>marina@mybox.com · marina.admin</small></div><Badge tone="success">Ativo</Badge><span><small>Último acesso</small><b>Ontem, 18:20</b></span><ChevronRight size={17} /></div></div>{modal === 'admin' && <Modal title="Novo APP_ADMIN" description="Esta conta terá acesso global aos mercadinhos." onClose={() => setModal(null)} footer={<><Button variant="quiet" onClick={() => setModal(null)}>Cancelar</Button><Button variant="primary" onClick={() => { setModal(null); setToast('Administrador criado e acesso liberado') }}>Criar administrador</Button></>}><div className="form-grid"><Field label="Nome"><input placeholder="Nome completo" /></Field><Field label="Username"><input placeholder="usuario.admin" /></Field><Field label="E-mail"><input type="email" placeholder="email@mybox.com" /></Field><Field label="Senha inicial"><input type="password" /></Field></div><div className="admin-warning"><ShieldCheck size={18} /><span>A conta poderá criar mercados e outros administradores.</span></div></Modal>}{toast && <Toast message={toast} onClose={() => setToast('')} />}</div>
  }

  const marketsContent = <>
    <div className="filterbar"><label className="filter-search"><Search size={18} /><input placeholder="Buscar mercadinho, cidade ou usuário" /></label><button><Filter size={17} /> Ativos</button></div>
    <div className="responsive-table markets-table"><div className="responsive-table__head"><span>Mercadinho</span><span>Conta de acesso</span><span>Vendas no mês</span><span>Último acesso</span><span>Status</span><span /></div>{markets.map((market) => <button className="responsive-table__row" key={market.id} onClick={() => setSelectedMarket(market)}><span data-label="Mercadinho" className="market-cell"><span><Store size={18} /></span><span><strong>{market.name}</strong><small>{market.city}</small></span></span><strong data-label="Conta">{market.user}</strong><strong data-label="Vendas">{market.sales}</strong><span data-label="Acesso">{market.lastAccess}</span><span data-label="Status"><Badge tone={market.active ? 'success' : 'neutral'}>{market.active ? 'Ativo' : 'Inativo'}</Badge></span><ChevronRight size={17} /></button>)}</div>
  </>

  return <div className="page admin-page"><PageHeader eyebrow="My Box · APP_ADMIN" title={section === 'global' ? 'Visão global' : 'Mercadinhos'} description={section === 'global' ? 'Saúde da plataforma e mercados cadastrados.' : 'Crie contas e controle o acesso dos mercados.'} actions={<Button variant="primary" icon={<Plus size={18} />} onClick={() => setModal('market')}>Novo mercadinho</Button>} />
    {section === 'global' && <><div className="admin-hero"><div><span>Plataforma operando normalmente</span><strong>3 mercados ativos agora</strong><small><Activity size={15} /> Última verificação há 20 segundos</small></div><div><Metric label="Mercados ativos" value="3" detail="1 inativo" tone="success" icon={<Store size={18} />} /><Metric label="Vendas no mês" value="R$ 56.005" detail="+11,8%" tone="success" icon={<CircleDollarSign size={18} />} /><Metric label="Contas de acesso" value="6" detail="2 APP_ADMIN" icon={<UsersRound size={18} />} /></div></div><div className="admin-status-grid"><article><span><Check size={19} /></span><div><strong>API operacional</strong><small>Resposta média 182 ms</small></div><Badge tone="success">Disponível</Badge></article><article><span><Check size={19} /></span><div><strong>Backups diários</strong><small>4 de 4 concluídos</small></div><Badge tone="success">Em dia</Badge></article><article><span><Building2 size={19} /></span><div><strong>Novos mercados</strong><small>1 cadastro este mês</small></div><Badge tone="info">Julho</Badge></article></div><Section title="Mercadinhos recentes">{marketsContent}</Section></>}
    {section === 'markets' && marketsContent}
    {selectedMarket && <Modal title={selectedMarket.name} description={selectedMarket.city} onClose={() => setSelectedMarket(null)} footer={<><Button variant="quiet" onClick={() => setSelectedMarket(null)}>Fechar</Button><Button onClick={() => setToast('Dados do mercadinho atualizados')}>Editar</Button>{selectedMarket.active && <Button variant="danger" onClick={() => setModal('inactivate')}>Inativar</Button>}</>}><div className="detail-status"><Badge tone={selectedMarket.active ? 'success' : 'neutral'}>{selectedMarket.active ? 'Mercado ativo' : 'Mercado inativo'}</Badge><span><Store size={15} /> Criado em 04 mar 2026</span></div><div className="detail-summary"><span><small>Usuário</small><strong>{selectedMarket.user}</strong></span><span><small>Vendas no mês</small><strong>{selectedMarket.sales}</strong></span><span><small>Último acesso</small><strong>{selectedMarket.lastAccess}</strong></span></div><Section title="Conta compartilhada"><div className="security-row"><span><ShieldCheck size={20} /></span><div><strong>{selectedMarket.user}@mybox.com</strong><small>Acesso MERCADO · senha protegida</small></div><Button>Redefinir senha</Button></div></Section></Modal>}
    {modal === 'market' && <Modal title="Novo mercadinho" description="O cadastro público está desativado; o acesso será criado aqui." onClose={() => setModal(null)} size="large" footer={<><Button variant="quiet" onClick={() => setModal(null)}>Cancelar</Button><Button variant="primary" onClick={() => { setModal(null); setToast('Mercadinho e conta de acesso criados') }}>Criar mercadinho</Button></>}><Section title="Dados do mercado"><div className="form-grid"><Field label="Nome"><input placeholder="Nome do mercadinho" /></Field><Field label="CNPJ (opcional)"><input placeholder="00.000.000/0000-00" /></Field><Field label="Telefone (opcional)"><input placeholder="(00) 00000-0000" /></Field><Field label="Status"><select><option>Ativo</option><option>Inativo</option></select></Field></div></Section><Section title="Conta de acesso"><div className="form-grid"><Field label="Nome do responsável"><input placeholder="Nome" /></Field><Field label="Username"><input placeholder="usuario.mercado" /></Field><Field label="E-mail"><input type="email" placeholder="email@mercado.com" /></Field><Field label="Senha inicial"><input type="password" /></Field></div></Section></Modal>}
    {modal === 'inactivate' && selectedMarket && <Modal title={`Inativar ${selectedMarket.name}?`} description="O histórico será preservado, mas novos acessos e operações serão bloqueados." onClose={() => setModal(null)} size="small" footer={<><Button variant="quiet" onClick={() => setModal(null)}>Manter ativo</Button><Button variant="danger" onClick={() => { setModal(null); setSelectedMarket(null); setToast('Mercadinho inativado com histórico preservado') }}>Confirmar inativação</Button></>}><div className="admin-warning"><ShieldCheck size={18} /><span>Vendas, estoque, financeiro e fiado continuarão disponíveis para auditoria.</span></div></Modal>}
    {toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>
}

