import { useState } from 'react'
import { AlertTriangle, Banknote, Building2, CalendarDays, Check, ChevronRight, CircleDollarSign, CreditCard, Filter, Landmark, Plus, ReceiptText, Search, TrendingDown, TrendingUp, WalletCards } from 'lucide-react'
import { accounts, firms, money } from '../data/mockData'
import type { Account, Firm } from '../types'
import { Badge, Button, Field, Metric, Modal, PageHeader, Progress, Section, Toast } from '../components/Ui'

export function FinancePage() {
  const [tab, setTab] = useState<'visao' | 'contas' | 'margens'>('visao')
  const [selected, setSelected] = useState<Account | null>(null)
  const [modal, setModal] = useState<'account' | 'pay' | null>(null)
  const [toast, setToast] = useState('')

  const toneFor = (status: Account['status']) => status === 'Paga' ? 'success' : status === 'Vencida' ? 'danger' : status === 'Cancelada' ? 'neutral' : 'warning'

  const markPaid = () => {
    setModal(null)
    setSelected(null)
    setToast('Conta marcada como paga e incluída no resumo financeiro')
  }

  return (
    <div className="page">
      <PageHeader eyebrow="Atualizado em tempo real" title="Financeiro" description="Vendas, recebimentos e despesas no mesmo período." actions={<Button variant="primary" icon={<Plus size={18} />} onClick={() => setModal('account')}>Nova conta</Button>} />
      <div className="page-tabs"><button className={tab === 'visao' ? 'active' : ''} onClick={() => setTab('visao')}>Visão geral</button><button className={tab === 'contas' ? 'active' : ''} onClick={() => setTab('contas')}>Contas</button><button className={tab === 'margens' ? 'active' : ''} onClick={() => setTab('margens')}>Margens</button></div>

      {tab === 'visao' && <>
        <div className="period-bar"><div className="role-switch"><button className="active">Hoje</button><button>Este mês</button><button>Personalizado</button></div><button><CalendarDays size={17} /> 17 jul 2026</button></div>
        <section className="finance-balance"><div><span>Saldo operacional hoje</span><strong>R$ 2.360,88</strong><small><TrendingUp size={15} /> Entradas superam as saídas em 82%</small></div><div className="finance-flow"><span><i className="income"><TrendingUp size={18} /></i><span><small>Entradas</small><b>R$ 2.847,60</b></span></span><span><i className="expense"><TrendingDown size={18} /></i><span><small>Saídas</small><b>R$ 486,72</b></span></span></div></section>
        <div className="metrics-grid metrics-grid--five"><Metric label="Vendas finalizadas" value="R$ 3.095,90" detail="42 vendas" icon={<ReceiptText size={18} />} /><Metric label="Recebido" value="R$ 2.847,60" detail="Dinheiro, Pix e cartão" tone="success" icon={<Banknote size={18} />} /><Metric label="Fiado" value="R$ 248,30" detail="3 vendas" tone="warning" icon={<WalletCards size={18} />} /><Metric label="Contas abertas" value="R$ 3.420,00" detail="2 lançamentos" icon={<CreditCard size={18} />} /><Metric label="Vencidas" value="R$ 486,72" detail="1 conta" tone="danger" icon={<AlertTriangle size={18} />} /></div>
        <div className="dashboard-grid"><Section title="Fluxo dos últimos 7 dias"><div className="finance-chart"><div className="finance-chart__legend"><span><i className="income" />Entradas</span><span><i className="expense" />Saídas</span></div><div className="finance-chart__bars">{[[45, 18], [58, 22], [42, 35], [74, 28], [62, 38], [88, 31], [68, 16]].map(([income, expense], index) => <span key={index}><i className="income" style={{ height: `${income}%` }} /><i className="expense" style={{ height: `${expense}%` }} /><small>{['Sáb', 'Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex'][index]}</small></span>)}</div></div></Section><Section title="Próximos vencimentos" action={<Button variant="quiet" onClick={() => setTab('contas')}>Ver contas</Button>}><div className="account-mini-list">{accounts.filter((account) => account.status !== 'Paga').map((account) => <button key={account.id} onClick={() => setSelected(account)}><span className={`due-date due-date--${toneFor(account.status)}`}><b>{account.vencimento.split(' ')[0]}</b><small>JUL</small></span><span><strong>{account.descricao}</strong><small>{account.firma ?? account.tipo}</small></span><b>{money(account.valor)}</b></button>)}</div></Section></div>
      </>}

      {tab === 'contas' && <>
        <div className="filterbar"><label className="filter-search"><Search size={18} /><input placeholder="Buscar descrição ou firma" /></label><button><CalendarDays size={17} /> Julho</button><button><Filter size={17} /> Status</button></div>
        <div className="status-summary"><button><span className="status-dot warning" /><span><small>Em aberto</small><b>{money(accounts.filter((account) => account.status === 'Em aberto').reduce((sum, account) => sum + account.valor, 0))}</b></span></button><button><span className="status-dot danger" /><span><small>Vencidas</small><b>{money(accounts.filter((account) => account.status === 'Vencida').reduce((sum, account) => sum + account.valor, 0))}</b></span></button><button><span className="status-dot success" /><span><small>Pagas no mês</small><b>{money(4280)}</b></span></button></div>
        <div className="responsive-table account-table"><div className="responsive-table__head"><span>Conta</span><span>Tipo</span><span>Firma</span><span>Vencimento</span><span>Valor</span><span>Status</span><span /></div>{accounts.map((account) => <button className="responsive-table__row" key={account.id} onClick={() => setSelected(account)}><span data-label="Conta"><strong>{account.descricao}</strong><small>Lançada em 02 jul</small></span><span data-label="Tipo">{account.tipo}</span><span data-label="Firma">{account.firma ?? 'Sem vínculo'}</span><strong data-label="Vencimento">{account.vencimento}</strong><strong data-label="Valor">{money(account.valor)}</strong><span data-label="Status"><Badge tone={toneFor(account.status)}>{account.status}</Badge></span><ChevronRight size={17} /></button>)}</div>
      </>}

      {tab === 'margens' && <div className="margin-page"><div className="margin-hero"><div><span>Margem média estimada</span><strong>27,8%</strong><small>Baseada no custo e preço atual das apresentações.</small></div><div><span><small>Melhor margem</small><b>Óleo de Soja · Unidade</b><strong>28,1%</strong></span><span><small>Requer atenção</small><b>Arroz · Fardo 10 kg</b><strong className="text-warning">27,1%</strong></span></div></div><div className="responsive-table margin-table"><div className="responsive-table__head"><span>Produto</span><span>Apresentação</span><span>Custo estimado</span><span>Preço</span><span>Margem</span></div>{[['Feijão Carioca', '1 kg', 5.15, 7], ['Feijão Carioca', 'Fardo 10 kg', 51.5, 68], ['Arroz Branco', 'Fardo 10 kg', 43, 59], ['Óleo de Soja', 'Unidade', 6.4, 8.9]].map(([product, presentation, cost, price]) => { const margin = ((Number(price) - Number(cost)) / Number(price)) * 100; return <div className="responsive-table__row" key={`${product}-${presentation}`}><strong data-label="Produto">{product}</strong><span data-label="Apresentação">{presentation}</span><span data-label="Custo">{money(Number(cost))}</span><strong data-label="Preço">{money(Number(price))}</strong><span data-label="Margem" className="margin-cell"><Progress value={margin} tone="success" /><b>{margin.toFixed(1)}%</b></span></div> })}</div></div>}

      {selected && !modal && <Modal title={selected.descricao} description={`${selected.tipo} · lançamento 02 jul 2026`} onClose={() => setSelected(null)} footer={<><Button variant="quiet" onClick={() => setSelected(null)}>Fechar</Button>{selected.status !== 'Paga' && selected.status !== 'Cancelada' && <Button variant="primary" icon={<Check size={17} />} onClick={() => setModal('pay')}>Marcar como paga</Button>}</>}><div className="detail-status"><Badge tone={toneFor(selected.status)}>{selected.status}</Badge>{selected.firma && <span><Building2 size={15} /> {selected.firma}</span>}</div><div className="detail-summary"><span><small>Valor</small><strong>{money(selected.valor)}</strong></span><span><small>Vencimento</small><strong>{selected.vencimento}</strong></span><span><small>Tipo</small><strong>{selected.tipo}</strong></span></div><Field label="Observação"><textarea defaultValue="Lançamento referente ao movimento mensal." /></Field></Modal>}
      {modal === 'pay' && selected && <Modal title="Confirmar pagamento" description={selected.descricao} onClose={() => setModal(null)} footer={<><Button variant="quiet" onClick={() => setModal(null)}>Cancelar</Button><Button variant="primary" onClick={markPaid}>Confirmar {money(selected.valor)}</Button></>}><div className="form-grid"><Field label="Data do pagamento"><input type="date" defaultValue="2026-07-17" /></Field><Field label="Conta de saída"><select><option>Caixa do mercado</option><option>Conta corrente</option></select></Field></div><Field label="Observação"><textarea placeholder="Opcional" /></Field></Modal>}
      {modal === 'account' && <Modal title="Nova conta financeira" description="Registre boletos, notas, compras e outras despesas." size="large" onClose={() => setModal(null)} footer={<><Button variant="quiet" onClick={() => setModal(null)}>Cancelar</Button><Button variant="primary" onClick={() => { setModal(null); setToast('Conta financeira criada em aberto') }}>Salvar conta</Button></>}><div className="form-grid"><Field label="Descrição"><input placeholder="Descrição da conta" /></Field><Field label="Tipo"><select><option>Boleto</option><option>Nota</option><option>Compra de mercadoria</option><option>Despesa</option><option>Outro</option></select></Field><Field label="Firma (opcional)"><select><option>Sem vínculo</option>{firms.filter((firm) => firm.ativo).map((firm) => <option key={firm.id}>{firm.nome}</option>)}</select></Field><Field label="Valor"><input type="number" placeholder="R$ 0,00" /></Field><Field label="Data de lançamento"><input type="date" defaultValue="2026-07-17" /></Field><Field label="Vencimento (opcional)"><input type="date" /></Field></div><Field label="Observação"><textarea placeholder="Informações adicionais" /></Field></Modal>}
      {toast && <Toast message={toast} onClose={() => setToast('')} />}
    </div>
  )
}

export function FirmsPage() {
  const [selected, setSelected] = useState<Firm | null>(null)
  const [newFirm, setNewFirm] = useState(false)
  const [toast, setToast] = useState('')

  return <div className="page"><PageHeader eyebrow="Limites de compra" title="Firmas e CNPJs" description="Acompanhe o uso mensal e as contas vinculadas." actions={<Button variant="primary" icon={<Plus size={18} />} onClick={() => setNewFirm(true)}>Nova firma</Button>} />
    <div className="firm-overview"><Metric label="Limite total" value={money(firms.reduce((sum, firm) => sum + (firm.ativo ? firm.limite : 0), 0))} detail="2 firmas ativas" icon={<Landmark size={18} />} /><Metric label="Utilizado no mês" value={money(firms.reduce((sum, firm) => sum + firm.utilizado, 0))} detail="68,5% do limite" tone="warning" icon={<CreditCard size={18} />} /><Metric label="Disponível" value={money(firms.reduce((sum, firm) => sum + Math.max(0, firm.limite - firm.utilizado), 0))} detail="Para novas compras" tone="success" icon={<CircleDollarSign size={18} />} /></div>
    <div className="filterbar"><label className="filter-search"><Search size={18} /><input placeholder="Buscar nome ou CNPJ" /></label><button><Filter size={17} /> Ativas</button></div>
    <div className="firm-grid">{firms.map((firm) => { const percent = (firm.utilizado / firm.limite) * 100; return <button className={`firm-card ${!firm.ativo ? 'firm-card--inactive' : ''}`} key={firm.id} onClick={() => setSelected(firm)}><div className="firm-card__head"><span><Building2 size={20} /></span><Badge tone={firm.ativo ? 'success' : 'neutral'}>{firm.ativo ? 'Ativa' : 'Inativa'}</Badge></div><strong>{firm.nome}</strong><small>{firm.cnpj}</small><div className="firm-card__usage"><span><small>Utilizado em julho</small><b>{money(firm.utilizado)}</b></span><Progress value={percent} tone={percent > 80 ? 'danger' : percent > 65 ? 'warning' : 'success'} /><span><small>{percent.toFixed(0)}% do limite</small><b>{money(Math.max(0, firm.limite - firm.utilizado))} disponível</b></span></div><div className="firm-card__foot"><span>{firm.responsavel}</span><ChevronRight size={17} /></div></button> })}</div>
    {selected && <Modal title={selected.nome} description={selected.cnpj} size="large" onClose={() => setSelected(null)} footer={<><Button variant="quiet" onClick={() => setSelected(null)}>Fechar</Button><Button>Editar firma</Button></>}><div className="detail-status"><Badge tone={selected.ativo ? 'success' : 'neutral'}>{selected.ativo ? 'Ativa' : 'Inativa'}</Badge>{!selected.ativo && <span>Histórico preservado · bloqueada para novos lançamentos</span>}</div><div className="firm-detail-balance"><span><small>Limite mensal</small><strong>{money(selected.limite)}</strong></span><span><small>Utilizado</small><strong>{money(selected.utilizado)}</strong></span><span><small>Disponível</small><strong>{money(Math.max(0, selected.limite - selected.utilizado))}</strong></span></div><Progress value={(selected.utilizado / selected.limite) * 100} tone={(selected.utilizado / selected.limite) > .8 ? 'danger' : 'warning'} /><Section title="Contas vinculadas"><div className="account-mini-list">{accounts.filter((account) => account.firma === selected.nome).map((account) => <button key={account.id}><span className="due-date due-date--warning"><b>{account.vencimento.split(' ')[0]}</b><small>JUL</small></span><span><strong>{account.descricao}</strong><small>{account.status}</small></span><b>{money(account.valor)}</b></button>)}</div></Section></Modal>}
    {newFirm && <Modal title="Nova firma" description="Cadastre um CNPJ para acompanhar o limite mensal de compras." onClose={() => setNewFirm(false)} footer={<><Button variant="quiet" onClick={() => setNewFirm(false)}>Cancelar</Button><Button variant="primary" onClick={() => { setNewFirm(false); setToast('Firma cadastrada como ativa') }}>Cadastrar firma</Button></>}><div className="form-grid"><Field label="Nome"><input placeholder="Razão ou nome de referência" /></Field><Field label="CNPJ"><input placeholder="00.000.000/0000-00" /></Field><Field label="Responsável"><input placeholder="Nome do responsável" /></Field><Field label="Limite mensal"><input type="number" placeholder="R$ 0,00" /></Field></div><Field label="Observação"><textarea placeholder="Opcional" /></Field></Modal>}
    {toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>
}

