import { useState } from 'react'
import { Archive, BarChart3, CalendarDays, Check, ChevronRight, CloudDownload, Database, Download, FileSpreadsheet, KeyRound, LockKeyhole, Mail, Plus, Save, ShieldCheck, Store, UserRound } from 'lucide-react'
import type { Role } from '../types'
import { money } from '../data/mockData'
import { Badge, Button, Field, Metric, PageHeader, Progress, Section, Toast } from '../components/Ui'

export function ReportsPage() {
  return <div className="page"><PageHeader eyebrow="Análises" title="Relatórios" description="Acompanhe vendas, margem, estoque e valores em aberto." actions={<Button icon={<Download size={18} />}>Exportar relatório</Button>} />
    <div className="report-picker"><button className="active"><BarChart3 size={20} /><span><strong>Vendas</strong><small>Movimento e pagamentos</small></span></button><button><Archive size={20} /><span><strong>Estoque</strong><small>Posição e movimentações</small></span></button><button><UserRound size={20} /><span><strong>Fiado</strong><small>Dívidas e recebimentos</small></span></button><button><FileSpreadsheet size={20} /><span><strong>Financeiro</strong><small>Entradas e despesas</small></span></button></div>
    <div className="period-bar"><div className="role-switch"><button className="active">7 dias</button><button>30 dias</button><button>Este ano</button></div><button><CalendarDays size={17} /> 11 a 17 jul</button></div>
    <div className="metrics-grid"><Metric label="Total vendido" value="R$ 24.680,40" detail="+8,2% período anterior" tone="success" /><Metric label="Vendas" value="364" detail="52 por dia" /><Metric label="Ticket médio" value="R$ 67,80" detail="+R$ 3,40" tone="success" /><Metric label="Valor em fiado" value="R$ 1.940,20" detail="7,8% das vendas" tone="warning" /></div>
    <div className="report-chart"><div className="report-chart__head"><div><strong>Vendas por dia</strong><small>Valores finalizados, incluindo fiado</small></div><Badge tone="info">R$ 24.680,40</Badge></div><div className="line-chart"><svg viewBox="0 0 800 240" role="img" aria-label="Gráfico de vendas dos últimos sete dias"><path className="line-chart__grid" d="M0 40H800M0 100H800M0 160H800M0 220H800" /><path className="line-chart__area" d="M0 185 C75 165,85 112,135 130 S220 175,270 124 S350 52,405 92 S500 145,550 74 S650 102,690 58 S755 74,800 40 L800 240 L0 240 Z" /><path className="line-chart__line" d="M0 185 C75 165,85 112,135 130 S220 175,270 124 S350 52,405 92 S500 145,550 74 S650 102,690 58 S755 74,800 40" /><g>{[[0,185],[135,130],[270,124],[405,92],[550,74],[690,58],[800,40]].map(([x,y], index) => <circle key={index} cx={x} cy={y} r="5" />)}</g></svg><div className="line-chart__labels"><span>Sáb</span><span>Dom</span><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span></div></div></div>
    <div className="dashboard-grid"><Section title="Produtos mais vendidos"><div className="ranking-list">{[['Feijão Carioca', 184, 92], ['Arroz Branco', 151, 76], ['Óleo de Soja', 124, 62], ['Açúcar Cristal', 87, 44]].map(([name, total, width], index) => <div key={String(name)}><span>{index + 1}</span><div><strong>{name}</strong><Progress value={Number(width)} tone="success" /></div><b>{total} un.</b></div>)}</div></Section><Section title="Formas de pagamento"><div className="donut-summary"><div className="donut"><span><strong>92%</strong><small>recebido</small></span></div><div><span><i className="money" />Dinheiro <b>R$ 8.391</b></span><span><i className="pix" />Pix <b>R$ 7.156</b></span><span><i className="card" />Cartão <b>R$ 7.193</b></span><span><i className="credit" />Fiado <b>R$ 1.940</b></span></div></div></Section></div>
  </div>
}

export function BackupsPage() {
  const [toast, setToast] = useState('')
  return <div className="page"><PageHeader eyebrow="Proteção dos dados" title="Backups e exportações" description="Acompanhe a cópia automática e gere arquivos para leitura." actions={<Button variant="primary" icon={<CloudDownload size={18} />} onClick={() => setToast('Exportação preparada e adicionada ao histórico')}>Nova exportação</Button>} />
    <section className="backup-status"><div className="backup-status__mark"><Check size={27} /></div><div><Badge tone="success">Backup concluído</Badge><h2>Seus dados estão protegidos</h2><p>Última cópia automática hoje às 03:00. A próxima está prevista para amanhã no mesmo horário.</p></div><div><span><small>Último backup</small><strong>17 jul, 03:00</strong></span><span><small>Tamanho</small><strong>48,2 MB</strong></span><span><small>Retenção</small><strong>30 dias</strong></span></div></section>
    <div className="backup-grid"><article><span className="backup-icon backup-icon--debt"><UserRound size={22} /></span><div><strong>Caderno de fiado</strong><p>Clientes, dívidas, vendas de origem e pagamentos.</p></div><Badge tone="success">Incluído diariamente</Badge><Button icon={<FileSpreadsheet size={17} />} onClick={() => setToast('Planilha de fiado gerada com sucesso')}>Exportar planilha</Button></article><article><span className="backup-icon"><Database size={22} /></span><div><strong>Base completa</strong><p>Estoque, vendas, financeiro, caixa e configurações.</p></div><Badge tone="info">Cópia técnica</Badge><Button icon={<Download size={17} />} onClick={() => setToast('Solicitação de backup completo registrada')}>Solicitar cópia</Button></article></div>
    <Section title="Histórico de exportações" action={<Badge tone="neutral">Últimos 30 dias</Badge>}><div className="responsive-table backup-table"><div className="responsive-table__head"><span>Arquivo</span><span>Conteúdo</span><span>Gerado em</span><span>Formato</span><span>Status</span><span /></div>{[['fiado-julho-2026.xlsx','Clientes e dívidas','17 jul, 09:12','Planilha'],['resumo-financeiro-junho.pdf','Financeiro','01 jul, 08:00','PDF'],['estoque-30-06-2026.xlsx','Posição de estoque','30 jun, 19:24','Planilha']].map(([file,content,date,format]) => <div className="responsive-table__row" key={file}><span data-label="Arquivo"><strong>{file}</strong><small>Mercadinho Coutinho</small></span><span data-label="Conteúdo">{content}</span><span data-label="Data">{date}</span><Badge tone="info">{format}</Badge><Badge tone="success">Disponível</Badge><Button variant="quiet" aria-label={`Baixar ${file}`} icon={<Download size={17} />} /></div>)}</div></Section>
    <div className="technical-note"><ShieldCheck size={18} /><span><strong>Armazenamento técnico pendente de definição</strong><small>O protótipo não escolhe provedor, volume ou política definitiva de restauração.</small></span></div>
    {toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>
}

export function AccountPage({ role }: { role: Role }) {
  const [toast, setToast] = useState('')
  return <div className="page account-page"><PageHeader eyebrow="Configurações" title={role === 'APP_ADMIN' ? 'Minha conta administrativa' : 'Minha conta'} description="Dados de acesso e segurança da sessão." actions={<Button variant="primary" icon={<Save size={18} />} onClick={() => setToast('Alterações salvas com sucesso')}>Salvar alterações</Button>} />
    <div className="settings-layout"><aside className="settings-nav"><button className="active"><UserRound size={18} />Perfil</button>{role === 'MERCADO' && <button><Store size={18} />Mercado</button>}<button><KeyRound size={18} />Senha e segurança</button><button><LockKeyhole size={18} />Sessões</button></aside><div className="settings-content"><Section title="Dados de acesso"><div className="profile-heading"><span className="profile-avatar">CO</span><div><strong>Coutinho</strong><small>{role === 'APP_ADMIN' ? 'Administrador global' : 'Conta compartilhada do mercado'}</small></div><Button>Alterar foto</Button></div><div className="form-grid"><Field label="Nome"><input defaultValue="Coutinho" /></Field><Field label="Username"><input defaultValue={role === 'APP_ADMIN' ? 'admin.mybox' : 'coutinho'} /></Field><Field label="E-mail"><input defaultValue={role === 'APP_ADMIN' ? 'admin@mybox.com' : 'coutinho@mybox.com'} /></Field><Field label="Tipo de conta"><input value={role} readOnly /></Field></div></Section>{role === 'MERCADO' && <Section title="Dados do mercado"><div className="form-grid"><Field label="Nome do mercado"><input defaultValue="Mercadinho Coutinho" /></Field><Field label="CNPJ"><input defaultValue="42.681.920/0001-30" /></Field><Field label="Telefone"><input defaultValue="(85) 98820-7740" /></Field><Field label="Cidade"><input defaultValue="Fortaleza, CE" /></Field></div></Section>}<Section title="Segurança"><div className="security-row"><span><ShieldCheck size={20} /></span><div><strong>Senha atualizada</strong><small>Última alteração há 34 dias</small></div><Button>Trocar senha</Button></div><div className="security-row"><span><LockKeyhole size={20} /></span><div><strong>1 sessão ativa</strong><small>Windows · Fortaleza · agora</small></div><Button variant="danger">Encerrar outras</Button></div></Section></div></div>
    {toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>
}

